/* Generated By:JavaCC: Do not edit this line. LogoConstants.java */
package lym.languages;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LogoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING = 3;
  /** RegularExpression Id. */
  int STRING1 = 4;
  /** RegularExpression Id. */
  int NUMERO = 5;
  /** RegularExpression Id. */
  int SPACE = 6;
  /** RegularExpression Id. */
  int OPERADORBOOLEANO = 7;
  /** RegularExpression Id. */
  int TEXTO = 8;
  /** RegularExpression Id. */
  int CHANGESHAPETOKEN = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "<STRING>",
    "<STRING1>",
    "<NUMERO>",
    "<SPACE>",
    "<OPERADORBOOLEANO>",
    "<TEXTO>",
    "\"changeshape\"",
    "\"random\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"sum\"",
    "\"difference\"",
    "\"!\"",
    "\"\\n\"",
    "\"make\"",
    "\"for\"",
    "\"[\"",
    "\"]\"",
    "\"repeat\"",
    "\"forward\"",
    "\"fd\"",
    "\"back\"",
    "\"bk\"",
    "\"right\"",
    "\"rt\"",
    "\"left\"",
    "\"lt\"",
    "\"clearscreen\"",
    "\"cs\"",
    "\"penup\"",
    "\"pendown\"",
    "\"hideturtle\"",
    "\"showturtle\"",
    "\"home\"",
    "\"setx\"",
    "\"sety\"",
    "\"setxy\"",
    "\"setheading\"",
    "\"seth\"",
    "\"arc\"",
    "\"csh\"",
    "\"label\"",
    "\"setlabelheight\"",
    "\"setwidth\"",
    "\"setcolor\"",
    "\"print\"",
    "\"pos\"",
    "\"xcor\"",
    "\"ycor\"",
    "\"heading\"",
    "\"towards\"",
    "\"list\"",
    "\"to\"",
    "\"_\"",
    "\":\"",
    "\"if\"",
    "\"[stop]\"",
  };

}
