/* Generated By:JavaCC: Do not edit this line. LogoTokenManager.java */
package lym.languages;

/** Token Manager. */
public class LogoTokenManager implements LogoConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1000L) != 0L)
            return 4;
         if ((active0 & 0x13ffffffff998600L) != 0L)
         {
            jjmatchedKind = 4;
            return 2;
         }
         if ((active0 & 0x800000000000000L) != 0L)
            return 1;
         if ((active0 & 0x20000L) != 0L)
            return 13;
         return -1;
      case 1:
         if ((active0 & 0x13ffffffff998600L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 4;
               jjmatchedPos = 1;
            }
            return 2;
         }
         return -1;
      case 2:
         if ((active0 & 0x1fffffd55998600L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 4;
               jjmatchedPos = 2;
            }
            return 2;
         }
         return -1;
      case 3:
         if ((active0 & 0x1f7cffd55890600L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 4;
               jjmatchedPos = 3;
            }
            return 2;
         }
         return -1;
      case 4:
         if ((active0 & 0xc7c63d11810600L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 4;
            return 2;
         }
         return -1;
      case 5:
         if ((active0 & 0xc3843901810600L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 5;
            return 2;
         }
         return -1;
      case 6:
         if ((active0 & 0xc3843901010200L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 6;
            return 2;
         }
         return -1;
      case 7:
         if ((active0 & 0x3843100010200L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 7;
            return 2;
         }
         return -1;
      case 8:
         if ((active0 & 0x843100010200L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 8;
            return 2;
         }
         return -1;
      case 9:
         if ((active0 & 0x843100010200L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 9;
            return 2;
         }
         return -1;
      case 10:
         if ((active0 & 0x800100000200L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 10;
            return 2;
         }
         return -1;
      case 11:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 11;
            return 2;
         }
         return -1;
      case 12:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 12;
            return 2;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 18);
      case 33:
         return jjStartNfaWithStates_0(0, 17, 13);
      case 42:
         return jjStopAtPos(0, 13);
      case 43:
         return jjStopAtPos(0, 11);
      case 45:
         return jjStartNfaWithStates_0(0, 12, 4);
      case 47:
         return jjStopAtPos(0, 14);
      case 58:
         return jjStartNfaWithStates_0(0, 59, 1);
      case 91:
         jjmatchedKind = 21;
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L);
      case 93:
         return jjStopAtPos(0, 22);
      case 95:
         return jjStopAtPos(0, 58);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x100000000000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0xc000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x200300000200L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x3100000L);
      case 104:
         return jjMoveStringLiteralDfa1_0(0x40005000000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1000000000000000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x1004000c0000000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0xc000c00000000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x30800400L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x38fa000008000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x280000000000000L);
      case 120:
         return jjMoveStringLiteralDfa1_0(0x10000000000000L);
      case 121:
         return jjMoveStringLiteralDfa1_0(0x20000000000000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x400004080400L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x30000000000000L);
      case 100:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(1, 4, 2);
         break;
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x438f8c40800000L);
      case 102:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 4, 2);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000200L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x100001010010000L);
      case 107:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(1, 4, 2);
         break;
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L);
      case 111:
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x88004001100000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x4100000000000L);
      case 115:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000200000000000L);
      case 116:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(1, 4, 2);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(1, 4, 2);
         break;
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000200L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L);
      case 99:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 4, 2);
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x40010000L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 104:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 4, 2);
         break;
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000L);
      case 107:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 109:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(2, 4, 2);
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0xc00000400L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x30002000000000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      case 114:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000L);
      case 115:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 4, 2);
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x20038f8000000000L);
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000100000000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000800000400L);
      case 101:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 2);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 2);
         return jjMoveStringLiteralDfa4_0(active0, 0x401000800000L);
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      case 104:
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x40010000000L);
      case 107:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 2);
         break;
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L);
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000200L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000000L);
      case 114:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 2);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 2);
         break;
      case 116:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 2);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 2);
         break;
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L);
      case 119:
         return jjMoveStringLiteralDfa4_0(active0, 0x1002001000000L);
      case 120:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
      case 121:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 4, 2);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x800001800000L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000010000L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x41000000000000L);
      case 108:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 2);
         break;
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000800000400L);
      case 112:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 2);
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000100000000L);
      case 116:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 2);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 2);
         return jjMoveStringLiteralDfa5_0(active0, 0x3000000000L);
      case 121:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 2);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 93:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(5, 61);
         break;
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x81000000000000L);
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x200L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000000L);
      case 109:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(5, 4, 2);
         break;
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000000L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x1010000L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L);
      case 116:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 4, 2);
         break;
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x3000000000L);
      case 119:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000L);
      case 100:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(6, 4, 2);
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000000L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000010000L);
      case 103:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 4, 2);
         break;
      case 110:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(6, 4, 2);
         break;
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000000L);
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x3000000000L);
      case 115:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 4, 2);
         return jjMoveStringLiteralDfa7_0(active0, 0x200L);
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 104:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 4, 2);
         return jjMoveStringLiteralDfa8_0(active0, 0x200L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000000L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000000L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000L);
      case 114:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 4, 2);
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x3000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x200L);
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000L);
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000000L);
      case 104:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000000L);
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x3000000000L);
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(9, 4, 2);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 4, 2);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 4, 2);
         return jjMoveStringLiteralDfa10_0(active0, 0x800100000000L);
      case 103:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 4, 2);
         break;
      case 112:
         return jjMoveStringLiteralDfa10_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(10, 4, 2);
         break;
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000000000L);
      case 110:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(10, 4, 2);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 103:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 104:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 116:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(13, 4, 2);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 14;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAddTwoStates(4, 5);
                  }
                  else if ((0x7000000000000000L & l) != 0L)
                  {
                     if (kind > 7)
                        kind = 7;
                  }
                  else if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 13;
                  else if (curChar == 32)
                  {
                     if (kind > 6)
                        kind = 6;
                     jjCheckNAdd(7);
                  }
                  else if (curChar == 45)
                     jjCheckNAdd(4);
                  else if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 1;
                  if (curChar == 62)
                     jjCheckNAdd(9);
                  else if (curChar == 60)
                     jjCheckNAdd(9);
                  break;
               case 3:
                  if (curChar == 45)
                     jjCheckNAdd(4);
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAddTwoStates(4, 5);
                  break;
               case 5:
                  if (curChar == 46)
                     jjCheckNAdd(6);
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(6);
                  break;
               case 7:
                  if (curChar != 32)
                     break;
                  kind = 6;
                  jjCheckNAdd(7);
                  break;
               case 8:
                  if ((0x7000000000000000L & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 9:
                  if (curChar == 61 && kind > 7)
                     kind = 7;
                  break;
               case 10:
                  if (curChar == 60)
                     jjCheckNAdd(9);
                  break;
               case 11:
                  if (curChar == 62)
                     jjCheckNAdd(9);
                  break;
               case 12:
                  if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 2:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAdd(2);
                  break;
               case 1:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 13:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjstateSet[jjnewStateCnt++] = 13;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 14 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, 
"\143\150\141\156\147\145\163\150\141\160\145", "\162\141\156\144\157\155", "\53", "\55", "\52", "\57", "\163\165\155", 
"\144\151\146\146\145\162\145\156\143\145", "\41", "\12", "\155\141\153\145", "\146\157\162", "\133", "\135", 
"\162\145\160\145\141\164", "\146\157\162\167\141\162\144", "\146\144", "\142\141\143\153", "\142\153", 
"\162\151\147\150\164", "\162\164", "\154\145\146\164", "\154\164", 
"\143\154\145\141\162\163\143\162\145\145\156", "\143\163", "\160\145\156\165\160", "\160\145\156\144\157\167\156", 
"\150\151\144\145\164\165\162\164\154\145", "\163\150\157\167\164\165\162\164\154\145", "\150\157\155\145", 
"\163\145\164\170", "\163\145\164\171", "\163\145\164\170\171", 
"\163\145\164\150\145\141\144\151\156\147", "\163\145\164\150", "\141\162\143", "\143\163\150", "\154\141\142\145\154", 
"\163\145\164\154\141\142\145\154\150\145\151\147\150\164", "\163\145\164\167\151\144\164\150", "\163\145\164\143\157\154\157\162", 
"\160\162\151\156\164", "\160\157\163", "\170\143\157\162", "\171\143\157\162", 
"\150\145\141\144\151\156\147", "\164\157\167\141\162\144\163", "\154\151\163\164", "\164\157", "\137", "\72", 
"\151\146", "\133\163\164\157\160\135", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3ffffffffffffff9L, 
};
static final long[] jjtoSkip = {
   0x6L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[14];
private final int[] jjstateSet = new int[28];
protected char curChar;
/** Constructor. */
public LogoTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public LogoTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 14; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x2200L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
